### ISSUE TITLE
Will not compile.

### ISSUE THREAD

**Issue by martinws** [XaeroDegreaz/SmartSocket#1]
I've downloaded the latest code.

It appears code does not compile it is missing net.smartsocket.protocols.binary.RemoteCall; 

The only RemoteCall in the download is in net.smartsocket.protocols.json; But this is deprecated.

**Comment by XaeroDegreaz** [comment]
Sorry about that! Yes, the new binary method is a lot better, but be warned, a new release has not been added to the download section, because I have not updated the Flash API to handle this new protocol.

If you are just interested in making your own client, then that's great. Anyhow, go ahead and have Git pull now -- I've pushed the missing class file (no idea how I missed that).

Thanks for the reports, and I would have gotten back to you sooner, but we've recently had a death in the family, so I've been gone.

**Comment by martinws** [comment]
Compiles. Note: Lots of warnings due to old RemoteClient dependencies in other classes.

**Comment by XaeroDegreaz** [comment]
In all honesty, unless you are trying to modify SmartSocket, or just get a deeper understanding of how the system works, you should just grab the releases from the downloads page.

The only code that relies on the non-binary version of RemoteCall is the SmartLobby code. I haven't yet retro-fitted (for a lack of better terms) the SmartLobby extension to use the new stuff.

The code in the trunk is not really release-worthy yet, thus no release download has been uploaded. I'm interested to know what warnings you are getting so that I can double check some things and make sure there isn't something else that I've neglected to upload.

Thanks again for your help.

**Comment by martinws** [comment]
Nothing too serious. 

Files like TCPExtension still importing net.smartsocket.protocols.json.RemoteCall
AbstractClient constructor/method conflict public void AbstractClient()
Unused variable in SmartSocketClient.java

Also I've got some general questions. Where would you like them posted? On Google Groups?

**Comment by XaeroDegreaz** [comment]
Yeah, those are just warnings because I've declared that RemoteCall method as deprecated in the JavaDoc. It's still completely valid to use, but I'd like to move away from using it, because the binary method now allows for the passing of file data through the stream instead of just text.

You can post them on Google Groups, or, if you'd like, you can just catch up with me on Google Talk: XaeroDegreaz if you'd like a faster response :)
